

services:

  dev-rdocker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RDOCKER_DEBUG=1
      - RDOCKER_CONTEXT=remote0
      - RDOCKER_REMOTE_HOST=remote0.example.com
      - RDOCKER_REMOTE_USER=docker
      - RDOCKER_TCP_ENABLE=1
      - RDOCKER_TCP_PORT=12345
      - RDOCKER_LOCAL_SOCKET=/rdocker/run/rdocker.sock
    volumes:
      - ~/.ssh:/home/rdocker/.ssh:ro
    ports:
      - "1234:12345"
    command:
      - rdocker
      - tunnel-up
