---
# This workflow will build a Docker image and push it to Docker Hub
#
# Required repo secrets:
# - DOCKERHUB_TOKEN
#
# Required repo variables:
# - DOCKERHUB_USERNAME
# - DOCKERHUB_REPONAME


name: Build docker image and publish to Docker Hub

on:
  push:
    tags:
      - "v*"

#env:
#  REPO_NAME: rdocker

jobs:
  publish:
    name: Publish image
    runs-on: ubuntu-latest
    environment: production

    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: vars
        run: |
          version=${GITHUB_REF_NAME#v}
          echo "version=$version" >> $GITHUB_OUTPUT
          
          image_tag_versioned=${{vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPONAME }}:${version}
          image_tag_latest=${{vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPONAME }}:latest
          echo "image_tag_versioned=$image_tag_versioned" >> $GITHUB_OUTPUT
          echo "image_tag_latest=$image_tag_latest" >> $GITHUB_OUTPUT

        #echo "major_minor=$(echo $version | cut -d. -f1,2)" >> $GITHUB_OUTPUT
        #echo "major=$(echo $version | cut -d. -f1)" >> $GITHUB_OUTPUT

      - name: Build, tag, and push image to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          sbom: true
          attests: true
          tags: |
            ${{ steps.vars.outputs.image_tag_versioned }}
            ${{ steps.vars.outputs.image_tag_latest }}
          # Caching
          #cache-from: type=gha
          #cache-to: type=gha,mode=max`


#      - name: Install Syft
#        run: |
#          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
#
#      - name: Install ORAS
#        uses: oras-project/setup-oras@v1
#
#      - name: Generate SBOM
#        run: |
#          syft ${{ steps.vars.outputs.image_tag_versioned }} -o spdx-json > sbom.spdx.json

#      - name: Attach SBOM using ORAS
#        run: |
#          oras attach \
#          --artifact-type application/spdx+json \
#          docker.io/${{ steps.vars.outputs.image_tag_versioned }} \
#          sbom.spdx.json:application/spdx+json

#    - name: Build, tag, and push image to Docker Hub
#      id: build-image
#      env:
#        #IMAGE_TAG: ${{ github.ref_type }}-${{ github.ref_name }}
#        IMAGE_TAG: ${{ github.ref_name }}
#        REGISTRY: ${{ vars.DOCKERHUB_USERNAME }}
#      run: |
#        docker build -t $REGISTRY/$REPO_NAME:$IMAGE_TAG .
#
#        docker push $REGISTRY/$REPO_NAME:$IMAGE_TAG
#
#        docker tag $REGISTRY/$REPO_NAME:$IMAGE_TAG $REGISTRY/$REPO_NAME:latest
#        docker push $REGISTRY/$REPO_NAME:latest
#
#        echo "image=$REGISTRY/$REPO_NAME:$IMAGE_TAG" >> $GITHUB_OUTPUT
