---
# This workflow will build a Docker image and push it to Docker Hub
#
# Required repo secrets:
# - DOCKERHUB_TOKEN
#
# Required repo variables:
# - DOCKERHUB_USERNAME
# - DOCKERHUB_REPONAME


name: Build docker image and publish to Docker Hub

on:
  push:
    tags:
      - "v*"

#env:
#  REPO_NAME: rdocker

jobs:
  publish:
    name: Publish image
    runs-on: ubuntu-latest
    environment: production

    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build, tag, and push image to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPONAME }}:${{ github.ref_name }}
            ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPONAME }}:latest
          # Caching
          #cache-from: type=gha
          #cache-to: type=gha,mode=max`


#    - name: Build, tag, and push image to Docker Hub
#      id: build-image
#      env:
#        #IMAGE_TAG: ${{ github.ref_type }}-${{ github.ref_name }}
#        IMAGE_TAG: ${{ github.ref_name }}
#        REGISTRY: ${{ vars.DOCKERHUB_USERNAME }}
#      run: |
#        docker build -t $REGISTRY/$REPO_NAME:$IMAGE_TAG .
#
#        docker push $REGISTRY/$REPO_NAME:$IMAGE_TAG
#
#        docker tag $REGISTRY/$REPO_NAME:$IMAGE_TAG $REGISTRY/$REPO_NAME:latest
#        docker push $REGISTRY/$REPO_NAME:latest
#
#        echo "image=$REGISTRY/$REPO_NAME:$IMAGE_TAG" >> $GITHUB_OUTPUT
